# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.choose_xls = QtWidgets.QPushButton(self.centralwidget)
        self.choose_xls.setGeometry(QtCore.QRect(130, 10, 75, 23))
        self.choose_xls.setObjectName("choose_xls")
        self.choose_csv = QtWidgets.QPushButton(self.centralwidget)
        self.choose_csv.setGeometry(QtCore.QRect(130, 40, 75, 23))
        self.choose_csv.setObjectName("choose_csv")
        self.xls_path = QtWidgets.QLineEdit(self.centralwidget)
        self.xls_path.setGeometry(QtCore.QRect(10, 10, 113, 20))
        self.xls_path.setObjectName("xls_path")
        self.csv_path = QtWidgets.QLineEdit(self.centralwidget)
        self.csv_path.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.csv_path.setObjectName("csv_path")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_xls.setText(_translate("MainWindow", "Choose XLS"))
        self.choose_csv.setText(_translate("MainWindow", "Choose CSV"))
